language: python

os:
  - linux

python:
  - "3.6"

install:
  - pip install numpy --upgrade
  - pip install .

# Run tests
script:
  - py.test tests/*.py -v

# Other stuff
notifications:
  email:
    - f.pinamartins@gmail.com
    - baptista.joao33@gmail.com
