site_name: pyRona Manual'
#site_favicon: 'assets/Icon.png'
site_author: Francisco Pina-Martins
repo_url: https://gitlab.com/StuntsPT/pyrona
edit_uri: tree/master/docs

pages:
    - 'Introduction': 'index.md'
    - 'Installation & dependencies': 'install.md'
    - 'Method description': 'description.md'
    - 'Usage': 'usage.md'
    - 'Wrappers':
        - 'Wrapping BayPass': 'baypass.md'
        - 'Wrapping LFMM': 'lfmm.md'
    - 'Output': 'output.md'
    - 'Citation': 'citation.md'
    - 'Future Plans': 'future.md'
    - 'FAQ': 'faq.md'
theme: readthedocs
